name: CI devops 2023

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout your GitHub code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      # Setup JDK 17 using actions/setup-java@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # AdoptOpenJDK's Eclipse Temurin distribution

      # Build your app with Maven
      - name: Build and test with Maven
        run: mvn clean install # or another Maven command like 'mvn package' or 'mvn test'
